/**
 * Canonical audit action names.
 *
 * Kept as a closed union so a typo cannot silently create a new action name
 * that nothing queries for.
 */
export const AUDIT_ACTIONS = [
  'TICKET_CREATED',
  'TICKET_CLOSED',
  'TICKET_ARCHIVED',
  'DEAL_PARTNER_ADDED',
  'ROLES_ASSIGNED',
  'DEAL_DETAILS_SUBMITTED',
  'BUYER_APPROVED',
  'BUYER_REQUESTED_CHANGES',
  'PAYMENT_CURRENCY_SELECTED',
  'PAYOUT_CURRENCY_SELECTED',
  'PAYMENT_REQUEST_CREATED',
  'PAYMENT_DETECTED',
  'PAYMENT_CONFIRMED',
  'BUYER_COMPLETED',
  'SELLER_COMPLETED',
  'PAYOUT_ADDRESS_SUBMITTED',
  'PAYOUT_APPROVED',
  'PAYOUT_REJECTED',
  'PAYOUT_BROADCAST',
  'PAYOUT_CONFIRMED',
  'SELLER_CONFIRMED_RECEIPT',
  'SELLER_REPORTED_MISSING_FUNDS',
  'DISPUTE_OPENED',
  'DISPUTE_RESOLVED',
  'DEAL_CANCELLED',
  'DEAL_EXPIRED',
  'STATE_TRANSITION',
  'CONFIG_UPDATED',
  'UNAUTHORIZED_ATTEMPT',
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
